### ISSUE TITLE
Psk1Stream.Dispose exception

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/peer-talk#36]
```
[xUnit.net @6:00:11.35] Catalyst .Node.Core.IntegrationTests .Modules .Dfs .DfsTest.DFS_should_add_and_read_binary [FAIL]
The active test run was aborted. Reason:  Unhandled Exception: 
System.IO.IOException: Unable to write data to the transport connection: 
Broken pipe. 
---> System.Net.Sockets.SocketException: Broken pipe
at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
--- End of inner exception stack trace ---
at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
at System.IO.BufferedStream.Flush()
at JuiceStream.DuplexBufferedStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at PeerTalk.StatsStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at PeerTalk.SecureCommunication.Psk1Stream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at PeerTalk.PeerConnection.ReadMessages(CancellationToken cancel)
at System. Threading. ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System. Threading. ThreadPoolWorkQueue .Dispatch()
```

**Comment by richardschneider** [comment]
From the stack trace it looks like the underlying socket was closed while reading a message.  Also note, that `BufferedStream.Flush` is being called; this indicates that some data for remote was not sent.
